"""
Project Prism
XSD Value Provider
"""

from decimal import Decimal


class XSDValueProvider:

    # --------------------------------------------------

    def supports(
        self,
        element,
    ):

        xsd_type = element.resolved_type

        if xsd_type is None:
            return False

        #
        # A type containing normal child elements is handled
        # by XMLBuilder.
        #
        # simpleContent is different: its value is still
        # generated by this provider.
        #

        elements = getattr(
            xsd_type,
            "elements",
            None,
        )

        simple_content = getattr(
            xsd_type,
            "simple_content",
            None,
        )

        if elements and simple_content is None:
            return False

        return True

    # --------------------------------------------------

    def get(
        self,
        element,
        context,
    ):

        xsd_type = element.resolved_type

        if xsd_type is None:
            return None

        #
        # Normal complex types are handled by XMLBuilder.
        #
        # A simpleContent type is still a value-bearing type.
        #

        elements = getattr(
            xsd_type,
            "elements",
            None,
        )

        simple_content = getattr(
            xsd_type,
            "simple_content",
            None,
        )

        if elements and simple_content is None:
            return None

        #
        # Resolve the complete simple-type inheritance chain.
        #

        type_chain = self._type_chain(
            xsd_type,
        )

        #
        # Enumeration has highest priority.
        #

        value = self._enumeration_value(
            type_chain,
        )

        if value is not None:
            return value

        #
        # Pattern has priority over generic datatype generation.
        #

        pattern = self._first_constraint(
            type_chain,
            "pattern",
        )

        if pattern:
            value = self._pattern_value(
                pattern,
                element,
            )

            if value is not None:
                return value

        #
        # Determine the underlying XSD datatype.
        #

        base = self._base_name(
            type_chain,
        )

        #
        if base in (
            "xs:gYear",
            "gYear",
        ):
            return "2026"
        #
        if base in (
            "xs:base64Binary",
            "base64Binary",
        ):
            return "UGF5bWVudFN0dWRpbw=="
        #
        # Boolean
        #

        if base in (
            "xs:boolean",
            "boolean",
        ):
            return "true"

        #
        # Date
        #

        if base in (
            "xs:date",
            "date",
        ):
            return "2026-01-01"

        #
        # DateTime
        #

        if base in (
            "xs:dateTime",
            "dateTime",
        ):
            return "2026-01-01T12:00:00"

        #
        # Time
        #

        if base in (
            "xs:time",
            "time",
        ):
            return "12:00:00"

        #
        # Decimal
        #

        if base in (
            "xs:decimal",
            "decimal",
        ):
            return self._decimal_value(
                type_chain,
            )

        #
        # Integer family
        #

        if base in (
            "xs:integer",
            "xs:int",
            "xs:long",
            "xs:short",
            "xs:byte",
            "xs:nonNegativeInteger",
            "xs:positiveInteger",
            "xs:nonPositiveInteger",
            "xs:negativeInteger",
            "integer",
            "int",
            "long",
            "short",
            "byte",
            "nonNegativeInteger",
            "positiveInteger",
            "nonPositiveInteger",
            "negativeInteger",
        ):
            return self._integer_value(
                type_chain,
                base,
            )

        #
        # String family.
        #

        if base in (
            "xs:string",
            "string",
            "xs:normalizedString",
            "normalizedString",
            "xs:token",
            "token",
        ):
            return self._text_value(
                type_chain,
            )

        #
        # Last-resort safe value.
        #

        return self._safe_fallback(
            type_chain,
        )

    # --------------------------------------------------

    @staticmethod
    def _type_chain(
        xsd_type,
    ):
        """
        Return the type followed by all inherited base types.

        The project model may expose base either as a string
        or as another XSD type object.
        """

        chain = []

        current = xsd_type

        visited = set()

        while current is not None:

            identity = id(current)

            if identity in visited:
                break

            visited.add(
                identity,
            )

            chain.append(
                current,
            )

            base = getattr(
                current,
                "base",
                None,
            )

            if base is None:
                break

            #
            # If base is an object, continue walking it.
            #

            if hasattr(
                base,
                "base",
            ):
                current = base
                continue

            #
            # A string base is the end of the model chain.
            #

            break

        return chain

    # --------------------------------------------------

    @staticmethod
    def _base_name(
        type_chain,
    ):
        """
        Find the first usable base/type name in the
        inheritance chain.
        """

        for xsd_type in type_chain:

            name = getattr(
                xsd_type,
                "name",
                None,
            )

            if name in (
                "boolean",
                "date",
                "dateTime",
                "time",
                "decimal",
                "integer",
                "int",
                "long",
                "short",
                "byte",
                "nonNegativeInteger",
                "positiveInteger",
                "nonPositiveInteger",
                "negativeInteger",
                "string",
                "normalizedString",
                "token",
            ):
                return name

            base = getattr(
                xsd_type,
                "base",
                None,
            )

            if hasattr(
                base,
                "name",
            ):
                base_name = base.name

                if base_name:
                    return base_name

            if isinstance(
                base,
                str,
            ):
                return base

        return None

    # --------------------------------------------------

    @staticmethod
    def _enumeration_value(
        type_chain,
    ):
        """
        Enumeration may exist on the derived type or
        any inherited restriction.
        """

        for xsd_type in type_chain:

            enumerations = getattr(
                xsd_type,
                "enumerations",
                None,
            )

            if not enumerations:
                continue

            first = enumerations[0]

            value = getattr(
                first,
                "value",
                None,
            )

            if value is not None:
                return str(value)

            return str(first)

        return None

    # --------------------------------------------------

    @staticmethod
    def _first_constraint(
        type_chain,
        attribute,
    ):
        """
        Find the nearest value for a restriction facet.
        """

        for xsd_type in type_chain:

            value = getattr(
                xsd_type,
                attribute,
                None,
            )

            if value is not None:
                return value

        return None

    # --------------------------------------------------

    @classmethod
    def _text_value(
        cls,
        type_chain,
    ):

        minimum = cls._first_constraint(
            type_chain,
            "min_length",
        )

        maximum = cls._first_constraint(
            type_chain,
            "max_length",
        )

        #
        # Start with a conservative legal value.
        #

        length = 1

        if minimum is not None:
            length = max(
                length,
                int(minimum),
            )

        if maximum is not None:
            length = min(
                length,
                int(maximum),
            )

        return "X" * length

    # --------------------------------------------------

    @classmethod
    def _decimal_value(
        cls,
        type_chain,
    ):

        minimum = cls._first_constraint(
            type_chain,
            "min_inclusive",
        )

        minimum_exclusive = cls._first_constraint(
            type_chain,
            "min_exclusive",
        )

        maximum = cls._first_constraint(
            type_chain,
            "max_inclusive",
        )

        maximum_exclusive = cls._first_constraint(
            type_chain,
            "max_exclusive",
        )

        fraction_digits = cls._first_constraint(
            type_chain,
            "fraction_digits",
        )

        total_digits = cls._first_constraint(
            type_chain,
            "total_digits",
        )

        #
        # Choose a value inside the permitted range.
        #

        value = Decimal("1")

        if minimum is not None:

            value = Decimal(
                str(minimum),
            )

        elif minimum_exclusive is not None:

            value = Decimal(
                str(minimum_exclusive),
            ) + Decimal("1")

        elif maximum is not None:

            maximum_value = Decimal(
                str(maximum),
            )

            if value > maximum_value:
                value = maximum_value

        elif maximum_exclusive is not None:

            maximum_value = Decimal(
                str(maximum_exclusive),
            )

            if value >= maximum_value:
                value = maximum_value - Decimal("1")

        #
        # Apply fractionDigits.
        #

        if fraction_digits is not None:

            digits = int(
                fraction_digits,
            )

            if digits == 0:

                value = value.quantize(
                    Decimal("1"),
                )

            else:

                quantum = Decimal(
                    "1." + ("0" * digits),
                )

                value = value.quantize(
                    quantum,
                )

        #
        # totalDigits is handled conservatively.
        #

        if total_digits is not None:

            allowed = int(
                total_digits,
            )

            text = format(
                value,
                "f",
            )

            digits = len(
                text.replace(
                    ".",
                    "",
                ).replace(
                    "-",
                    "",
                ),
            )

            if digits > allowed:

                if fraction_digits is not None:

                    fraction = int(
                        fraction_digits,
                    )

                    integer_digits = max(
                        1,
                        allowed - fraction,
                    )

                    value = Decimal(
                        "1" + ("." + ("0" * fraction) if fraction else ""),
                    )

                else:

                    value = Decimal("1")

        return format(
            value,
            "f",
        )

    # --------------------------------------------------

    @classmethod
    def _integer_value(
        cls,
        type_chain,
        base,
    ):

        minimum = cls._first_constraint(
            type_chain,
            "min_inclusive",
        )

        minimum_exclusive = cls._first_constraint(
            type_chain,
            "min_exclusive",
        )

        maximum = cls._first_constraint(
            type_chain,
            "max_inclusive",
        )

        maximum_exclusive = cls._first_constraint(
            type_chain,
            "max_exclusive",
        )

        #
        # XSD integer-derived built-ins also carry
        # semantic constraints.
        #

        if base in (
            "xs:positiveInteger",
            "positiveInteger",
        ):
            value = 1

        elif base in (
            "xs:nonNegativeInteger",
            "nonNegativeInteger",
        ):
            value = 0

        elif base in (
            "xs:negativeInteger",
            "negativeInteger",
        ):
            value = -1

        elif base in (
            "xs:nonPositiveInteger",
            "nonPositiveInteger",
        ):
            value = 0

        else:
            value = 1

        if minimum is not None:
            value = max(
                value,
                int(minimum),
            )

        if minimum_exclusive is not None:
            value = max(
                value,
                int(minimum_exclusive) + 1,
            )

        if maximum is not None:
            value = min(
                value,
                int(maximum),
            )

        if maximum_exclusive is not None:
            value = min(
                value,
                int(maximum_exclusive) - 1,
            )

        return str(value)

    # --------------------------------------------------

    @staticmethod
    def _pattern_value(
        pattern,
        element,
    ):
        """
        Generic recognizers for common ISO 20022
        structural patterns.

        These are datatype-pattern recognizers,
        not message-specific field rules.
        """

        #
        # UUID / UETR-style UUID pattern.
        #

        if "[a-f0-9]{8}" in pattern and "4[a-f0-9]{3}" in pattern:

            return "123e4567-e89b-42d3-a456-" "426614174000"

        #
        # LEI-style:
        # 18 alphanumeric characters + 2 digits.
        #

        if "{18}" in pattern and "{2}" in pattern and "[A-Z0-9]" in pattern:

            return "549300ABCDEFGHIJKL12"

        #
        # Telephone-number style.
        #

        if "[0-9]{1,3}" in pattern and "[0-9()+\\-]{1,30}" in pattern:

            return "+91-1234567890"

        #
        # Generic uppercase/alphanumeric.
        #
        #
        #
        # Hex-encoded binary (e.g. ILP condition/fulfillment).
        #

        if "[0-9a-fA-F]" in pattern:

            return "1a2b3c4d5e6f7a8b"
        #
        #

        if "[A-Z0-9]" in pattern:

            return "A"

        #
        # Generic numeric pattern.
        #

        if "[0-9]" in pattern:

            return "1"

        #
        # We cannot safely infer an arbitrary regex.
        #

        return None

    # --------------------------------------------------

    @classmethod
    def _safe_fallback(
        cls,
        type_chain,
    ):
        """
        Last-resort value.

        Honour string length restrictions where possible
        rather than returning an arbitrary placeholder.
        """

        minimum = cls._first_constraint(
            type_chain,
            "min_length",
        )

        maximum = cls._first_constraint(
            type_chain,
            "max_length",
        )

        length = 1

        if minimum is not None:
            length = max(
                length,
                int(minimum),
            )

        if maximum is not None:
            length = min(
                length,
                int(maximum),
            )

        return "X" * length
